name: voice_control
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - scipy
  - pip
  - pip:
      - vosk>=0.3.45
      - sounddevice>=0.4.6
